### ISSUE TITLE
gtm init returns with a "No File needs Merging"

### ISSUE THREAD

**Issue by AKFourSeven** [git-time-metric/gtm#52] opened 2017-01-09 09:40 UTC
Hi,

running on a Mac OS 10.10, I found gtm and thought it seemed pretty cool and wanted to give it a shot.
But after installing and running an `gtm init`, I always get  "No file need merging".

Running a `git config --get-regexp alias`, I could see that `gtm` wasn't an alias of git merge.
I have found this stack post http://stackoverflow.com/questions/7854611/git-mergetool-reports-no-files-need-merging, but that didn't solved the issue either.

Also gtm report throws a `Git Time Metric is not initialized`

Am I missing something ?

**Comment by mschenk42** [comment] 2017-01-10 03:58
Did you run `gtm init` from within the root directory of an already initialized git repo?  Here's how you can test if it's working correctly.

- git init
- gtm init
- edit some files in your editor
- gtm status
- git add/commit
- gtm report

**Comment by AKFourSeven** [comment] 2017-01-10 10:30
Yes it was in a an already initialized repo.
`git init` returns the error I mentionned previously and the other `gtm`commands returns `Git Time Metric is not initialized`, is it not possible to use it in an already initialized repo ?

**Comment by mschenk42** [comment] 2017-01-11 01:40
GTM does not work with bare git repos, i.e. ```git init --bare```.  I'm guessing that is what the issue is.  You can check this by looking for the ```.git``` hidden directory in the root.  If it doesn't exist it's been initialized as a bare repo.

**Comment by AKFourSeven** [comment] 2017-01-13 14:10
There is a ```.git``` in both all the repo I have tested this. Any other thoughts ?

**Comment by mschenk42** [comment] 2017-01-13 22:31
Let's determine if it's an issue with just this repo or in general for all repos.  Can you try creating a new git repo and initialize gtm?   If would be helpful if you could also share the .git/config file for the repo that has been problematic.

**Comment by AKFourSeven** [comment] 2017-01-23 09:40
I tried with a newly initialized repo and it worked but it does not seem to work on existing repo (it is a shared repo by the way).

And here I shared with you the .gitconfig of the problematic repo (I had to hide some of the facts as it s not my personal repo), the file is truncated but the rest of the file only contains remote branches config

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = ************
	fetch = +refs/heads/*:refs/remotes/origin/*
```

**Comment by mschenk42** [comment] 2017-01-24 00:12
I don't see anything out of the ordinary for the git configuration.  

To make sure I understand the issue,  do you get the "No files need merging" when running `gtm init` or after initializing the repo and then trying to add/commit files?  

You should see something similar to this when running `gtm init`

```
Git Time Metric initialized for /Users/mschenk/Projects/platform-chef

     post-commit: gtm commit --yes
  alias.fetchgtm: fetch origin refs/notes/gtm-data:refs/notes/gtm-data
   alias.pushgtm: push origin refs/notes/gtm-data
notes.rewriteref: refs/notes/gtm-data
        terminal: true
      .gitignore: /.gtm/
            tags:
```

I have a few things for you to check. 

1. Try running `gtm status` after editing some files in your editor with the gtm plugin.  If it's recording properly you should see some time reported.

2. Check to see if the `.git/hooks/post-commit`  contains gtm.  If you can, please share the contents of this file.  This hook is what records the time in a git note associated with the commit.  If this is not firing properly you will not see time when running `gtm report`.

Note - there is bug I addressed in the last release (just the other day) that sets the full path for gtm in the post-commit hook.  You can see more here https://github.com/git-time-metric/gtm/issues/54.

**Comment by AKFourSeven** [comment] 2017-01-26 08:29
Ok I really don't know why, but it seems like it is working now...
Possible answer would be me from node v5 to node v6.9.0, but I am not really anyway I retried `gtm init` on an existing repo and it worked fine!

**Comment by mschenk42** [comment] 2017-01-27 00:56
Good to hear. 👍

**Closed by mschenk42** 2017-01-27 00:56 UTC
